Fix ItemTimer not updating
darkbot-reloaded/DarkBot pull request #105
Opened 2021-11-12 13:22 UTC by ODAKAB

yes

2021-11-12 13:22 UTC, pajtor commented
no

2021-11-12 16:12 UTC, Pablete1234 requested changes

2021-11-12 16:12 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/core/objects/slotbars/Item.java
> +        public void resetTimer() {
A function inside itemtimer does not need to call itself resetTimer, this is already the timer
just rename it to reset
```suggestion
        public void reset() {
```

2021-11-12 16:59 UTC, Pablete1234 requested changes
This does not compile

2021-11-13 01:39 UTC, Pablete1234 approved these changes

2021-11-13 03:52 UTC, merged