Linux
darkbot-reloaded/DarkBot pull request #113
Opened 2021-12-17 20:10 UTC by Alph4rd

2022-07-22 23:01 UTC, dm94 commented
I am completely unfamiliar with how it works.
But wouldn't it be possible to detect which operating system is being used and on that basis activate or deactivate functions?
I know that many offsets would have to be changed, but based on a global variable it could be set to use one or the other.

2022-07-22 23:04 UTC, fabio1999ita commented
> I am completely unfamiliar with how it works. But wouldn't it be possible to detect which operating system is being used and on that basis activate or deactivate functions? I know that many offsets would have to be changed, but based on a global variable it could be set to use one or the other.

yeah, should be also easy and need to adapt the download of API too

2022-07-22 23:47 UTC, Pablete1234 commented
> But wouldn't it be possible to detect which operating system is being used and on that basis activate or deactivate functions? I know that many offsets would have to be changed, but based on a global variable it could be set to use one or the other.

Yes, when this PR is to be merged, it will be with such capability to adapt automatically to the OS, atm, the changes in here have been slowly being refactored/merged into master to make this PR more lightweight (less OS-specific things), and when it gets to be a minimum set of differences, those differences will have to work off of a toggle based on the OS, which darkbot will handle automatically.

Regarding browser native APIs, the libraries for this are not redistributed alongside the rest of windows-based apis (yet) because this isn't merged (yet). When this gets official support and is merged into master, the main libs will simply download the correct natives for linux which will be diff to the ones from windows.

2022-12-11 10:23 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/config/Config.java
> +            public @Option @Dropdown BrowserApi BROWSER_API = BrowserApi.TANOS_API;
```suggestion
            public @Option @Dropdown BrowserApi BROWSER_API = OSUtils.isLinux() ? BrowserApi.TANOS_API : BrowserApi.KEKKA_PLAYER;
```

2022-12-11 12:16 UTC, Pablete1234 requested changes
This is generally looking very, very compatible with the current codebase, unlike in the past where it was many, many changes.

I believe the main thing is sprite offset change from 0x18 to 0x20 in a few places, all other offset changes need to be double-checked but i believe they're just dec to hex conversions with the same value.

Overall very happy to see this be so close to a merge

2022-12-11 12:16 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/core/manager/MapManager.java
> +        int size = API.readMemoryInt(array_data + 0x20);
these are equivalent except for the 0x18 -> 0x20 offset, readMemoryLong checks at every step of the way the ptr is valid now

2022-12-11 12:16 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/core/manager/MapManager.java
> +                && ByteUtils.readObjectName(API.readLong(viewAddress + 208)).contains("HUD");
Undo the change plz

2022-12-11 12:16 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/core/api/TanosAdapter.java
> +        }
This whole piece should be moved to somewhere more reusable, potentially either GameApiImpl, or GameApi.DirectInteraction, where it expects another method (sendNotification) to be implemented and just calls that, that makes it so kekka and tanos don't need to copy-paste this block

2022-12-11 12:16 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/core/manager/MouseManager.java
> +import com.github.manolo8.darkbot.core.entities.Box;
```suggestion
```

2022-12-11 12:16 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/core/utils/factory/EntityFactory.java
> +        return r;
```suggestion
        long trait = API.readMemoryLong(address, 0x30, 0x30, 0x10) & ByteUtils.ATOM_MASK;
        return API.readMemoryString(trait, 0x40, 0x20, 0x18, 0x10, 0x10, 0x18).trim();
```

2022-12-11 12:16 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/ApiErrors.java
> +        if (api != BrowserApi.TANOS_API)
```suggestion
        if (api != (OSUtil.isLinux() ? BrowserApi.TANOS_API : BrowserApi.KEKKA_PLAYER))
```

maybe `OSUtil.getDefaultAPI` that just does this logic and re-use it in the 3 places it's used at?

2022-12-23 15:21 UTC, Pablete1234 approved these changes

2022-12-23 15:21 UTC, merged