Add possibility to disable master password first time
darkbot-reloaded/DarkBot pull request #117
Opened 2021-12-23 00:49 UTC by fabio1999ita

old vs new (the layout can still be improved)

![image](https://user-images.githubusercontent.com/27001568/147171105-cf01bf74-407b-4c00-9987-49a15079e355.png)

2021-12-23 02:34 UTC, fabio1999ita commented
![video](https://user-images.githubusercontent.com/27001568/147179106-0aa8639f-541f-4e4c-8375-7b4c45fc218a.gif)

2021-12-23 03:52 UTC, fabio1999ita commented
![video](https://user-images.githubusercontent.com/27001568/147185539-049b1baf-c812-48b8-ad43-4064dc775c55.gif)

2021-12-23 22:07 UTC, Pablete1234 commented
Currently you're using the Message in the jdialog for the string, then adding an "option" (usually, the list of buttons to show on bottom-right) that is a whole jpanel with everything

Instead, send just one jpanel as the message, which contains a jlabel, the field, and the button
lastly, make the button be the windows' default button, that way it will appear blue hinting the user that it should be their action to click

2021-12-24 01:37 UTC, fabio1999ita commented
![video](https://user-images.githubusercontent.com/27001568/147305256-60926dd8-d651-4ef5-b5ad-d1348078db18.gif)

2021-12-25 17:42 UTC, Pablete1234 requested changes
Just a couple final touchups but it looks good :+1: 

keep up the good work

2021-12-25 17:42 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/gui/login/SavedLogins.java
> +            }
```suggestion
            pass.setEditable(e.getStateChange() != ItemEvent.SELECTED);
            button.setEnabled(pass.getPassword().length > 0 || e.getStateChange() == ItemEvent.SELECTED);
```

This logic can be cleaned up & simplified a bit

2021-12-25 17:42 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/gui/login/SavedLogins.java
> +        pass.getDocument().addDocumentListener((GeneralDocumentListener) e -> button.setEnabled(!new String(pass.getPassword()).isEmpty() || check.isSelected()));
```suggestion
        pass.getDocument().addDocumentListener((GeneralDocumentListener) e -> 
                button.setEnabled(pass.getPassword().length > 0 || check.isSelected());
```
This line is too long to read comfortably, split it into a new line, and also avoid the new String allocation each time

2022-01-08 05:15 UTC, merged