Removed Update in Handle Response
darkbot-reloaded/DarkBot pull request #143
Opened 2022-03-19 05:08 UTC by anjeshshrestha

2022-03-20 06:36 UTC, Pablete1234 requested changes
What i'm seeing  here is you're simply wanting to avoid calling update after getting a reponse

This approach is kinda flawed, since we *do* want to update when we get a response.
The main issue trying to be solved is concurrent updates as you're iterating, to solve that, just act on that.

A way to solve such things is to make a copy and act upon that copy:

```java
    public List<String> collectAll() {
        List<InProgress> toCollect = data.getInProgress().values().stream()
                .filter(ip -> !ip.getCollectable().equals("0")).collect(Collectors.toList());
        return toCollect.map(this::collect).map(InProgress::getId).collect(Collectors.toList());
    }
```
It requires allocating an extra list, but it solves the root issue and doesn't create the side-effect of things not being updated after handling a response

2022-03-20 17:17 UTC, anjeshshrestha commented
> 

this should definitely work for the dispatch update issue. 

for the auction, we dont really need to update for that case because it doesnt impact the values we bid and slows it down loading the page over again and parsing it

2022-03-23 07:39 UTC, Pablete1234 reviewed
Run the formatter, there's a bunch of missing spaces around the pr

2022-03-24 07:23 UTC, Pablete1234 approved these changes

2022-03-24 07:23 UTC, merged