collect instantly using prime coupon
darkbot-reloaded/DarkBot pull request #156
Opened 2022-06-12 04:02 UTC by anjeshshrestha

need to test

2022-06-12 14:29 UTC, Pablete1234 requested changes
Just a few format changes

Have you tested this, does it work as expected?

2022-06-12 14:29 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/backpage/DispatchManager.java
> +        if(retriever.getCreditCost() > main.statsManager.credits || retriever.getUridiumCost() > main.statsManager.uridium || retriever.getPermitCost() > data.getPermit()){
split line, it's too long
```suggestion
        if (retriever.getCreditCost() > main.statsManager.credits || 
                retriever.getUridiumCost() > main.statsManager.uridium || 
                retriever.getPermitCost() > data.getPermit()) {
```

2022-06-12 14:29 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/backpage/DispatchManager.java
> +            if(data.getPrimeCoupons() == 0) return handleResponse("Instant Collect Failed", progress.getId(), "No Prime Coupon Available For Instant Collection");
```suggestion
            if (data.getPrimeCoupons() == 0) 
                return handleResponse("Instant Collect Failed", progress.getId(), 
                        "No Prime Coupon Available For Instant Collection");
```

2022-06-15 06:27 UTC, anjeshshrestha commented
did test today, seems to be working good

2022-06-15 14:21 UTC, merged