update auction to ajax call
darkbot-reloaded/DarkBot pull request #229
Opened 2023-01-14 15:42 UTC by anjeshshrestha

Revised the auction manager load auction items by implementing an AJAX call to only load the necessary HTML section for displaying auction items. This improves page load speed and reduces data usage as the entire page and auction history no longer need to be loaded

2023-01-14 16:00 UTC, Pablete1234 requested changes

2023-01-14 17:03 UTC, anjeshshrestha commented on src/main/java/com/github/manolo8/darkbot/backpage/AuctionManager.java
> +                    .setParam ("command", "getAuctionList")
probably IDE, will check ide setting

2023-01-15 00:45 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/backpage/AuctionManager.java
> +            return data.parse(dataHtml.toString());
This just looks like a terrible hack, you're parsing a JSON output to produce a fake html output to re-parse again?

Consider refactoring this and just properly map the json data to the results you want, don't parse, then re-string it to parse it again

2023-02-09 22:22 UTC, anjeshshrestha commented
This is very hacky and does not allow bidding if there is captcha

2023-02-09 22:22 UTC, closed without merging