Added error popups
darkbot-reloaded/DarkBot pull request #40
Opened 2021-01-04 23:20 UTC by LeffPL

The provided code will check what was the real cause why the bot wasn't able to load the API and display the proper error message.

2021-01-05 19:04 UTC, Pablete1234 requested changes
This code is making many assumptions, many of them may never be true. 
General changes required:
  - You should try to extract most if not all of the strings to the translatable strrings file
  - Encapsulate this code elsewhere, the catch clausule of the error shouldn't be 200 lines long
  - Make the error handling happen first, user-oriented error eplaining later. Otherwise an error in your code may mask away the original error
   - You must not ever check for the system it's running on,  you should check what the error itself is. If the error says it can't run because it needs a 64bit system, then obviously that's a requirement, but not all apis may have this requirement and the code shouldn't assume it

2021-01-07 12:36 UTC, Leff-PL commented
Now the catch clausule is much shorter and I removed checking if the OS is 32-bit or not, since I'm not able to get this info from the error message (it's exactly the same as for 32-bit java).

The original error message remains untouched.

2021-01-07 15:35 UTC, Pablete1234 requested changes

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +
```suggestion
```

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +    private final String RUNTIME_LINK = "Download link: <a href=\"#\">" + RUNTIME_URL;
When you open an HTML tag you have to close it afterwards

Also have you tested if by adding an A with an actual href it lets you click it without needing to add a mouse listener?

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +        System.exit(0);
Excuse me what?

None of these errors are any reason to close the bot. The bot itself can run perfectly fine, it simply will have to be on no-op API.

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/resources/lang/strings_en.properties
> +api.errors.non_ansi_path=The bot folder path contains non-ANSI characters. Rename the folders<br/> where they occur or move the bot folder to D:/ and then run again
Make these messages the FULL html, with parameters for the things you may want to add separately, you can add parameters like `{0}` or `{1}` etc, then when doing `I18n.get` you add the parameters:

`I18n.get("some.string.resource", "param0", "param1")`

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +        JLabel unSuppJava    = new JLabel("<html>" + I18n.get("api.errors.unsupported_java"));
You open many html tags that you never close, nevertheless, move the whole message to the string itself and use parameters (see the other comment)

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +        });
This is quite ugly to add as a standalone, consider adding a util JHyperLink or similar that extends JLabel and has the logic for this

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/config/ConfigManager.java
> +            APIErrors err = new APIErrors();
An instance of APIErrors doesn't feel justified here whatsoever, make the class have static methods.

I think the only thing you should need is something along the lines of:

`String description = ApiErrors.createDescription(e)`

You can append that to the end of the original message, you can move it to the resources too and make it html in itself, with a parameter being the description.

Could end up looking something like:

```
The API you had selected is not able to load.
You probably do not have the required DLL in your lib folder.
The bot will start on no-operation API, change it in the settings and restart

In this case, it seems like you may be missing runtimes, download them here:
https://... 
```
The last part of that message would depend on what you find to be the issue

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +    JPanel pnl = new JPanel();
Make this class stateless and make everything static

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +        String[] folderNames = str.split("\\\\");
Use the filepath separator constant, not a hard-coded `\`

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/config/ConfigManager.java
> +            final String WORKING_DIR  = System.getProperty("user.dir");
Get the path from simply new File() or Paths, no need to access a system property for this

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/config/ConfigManager.java
> +            final String ERR_MSG      = e.getMessage();
The error is a nice thing if you wanna show it to the user, you can also use getLocalizedMessage to show it in the users' language

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/config/ConfigManager.java
> +            if      (ERR_MSG.contains(JAVA_32_ERR))          err.displayUnsupportedJavaError();
However, you should not be checking a contains in an error message. You never know if a different JVM implementation may show a different message and the program should never break due to that. Don't rely on the message, rely on the error instance

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/config/ConfigManager.java
> +            else if (!WORKING_DIR.matches("[\\x00-\\x7F]+")) err.displayInvalidPathError(WORKING_DIR);
Lastly, a suggested above, make the actual checking/deciding what error you show hidden away inside ApiErrors, none of that logic should be here

2021-01-07 15:35 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/APIErrors.java
> +        }
There's no need to do any for-loop, you can replace all of this with regex directly

2021-04-09 06:40 UTC, Pablete1234 commented
Since this has already been partially implemented and doesn't have much activity, i'll close

2021-04-09 06:40 UTC, closed without merging