Improve precision of library path
darkbot-reloaded/DarkBot pull request #94
Opened 2021-08-28 14:24 UTC by ODAKAB

Prevents loading from unwanted paths on odd cases.

2021-08-28 16:42 UTC, Pablete1234 requested changes

2021-08-28 16:42 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/LibUtils.java
> +    }
Don't call system.load from here, make this util just about returning a path, and call system.load in the class where it is used:

`System.load(LibUtils.getPath("DarkBoatAPI"));`
Also remove the need for the extension when calling, and add in the dll or so depending on the OS it runs on

2021-08-29 12:39 UTC, Pablete1234 requested changes

2021-08-29 12:39 UTC, Pablete1234 commented on src/main/java/com/github/manolo8/darkbot/utils/LibUtils.java
> +        return Paths.get("lib", library).toAbsolutePath().toString() + getExtension();
```suggestion
        return Paths.get("lib", library + getExtension()).toAbsolutePath().toString();
```
it's the file that has an extension, not an appended thing at the end of the path

2021-08-29 12:42 UTC, Pablete1234 approved these changes

2021-08-29 12:43 UTC, ODAKAB commented
Still works on my end after https://github.com/darkbot-reloaded/DarkBot/pull/94/commits/e4e6a928d0fb988626d8f3dc995662fcae9275cc

2021-09-26 10:17 UTC, merged